### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by lukemcdo** [tedd/Tedd.RandomUtils#1]
This library looks like something I'd like to use, but the GPL makes it tough to use. Is there any chance you could relicense to LGPL, MIT, or BSD? LGPL in particular looks like a great fit for this project.

**Comment by tedd** [comment]
Hi. Great point. I was under the impression that GPLv3 had opened for inclusion without the source code requirement, but seems my memory failed me. I'll flip it to MIT. 👍

**Comment by lukemcdo** [comment]
MIT is appreciated but LGPL is also a great option if you want people to contribute back their changes. MIT allows businesses to ship forks of your library without open-sourcing the changes, while (as best as I understand it) LGPL does not. But MIT is better understood, so that makes sense too.

Thanks for the prompt change!
